export const GET_UNITS_REQUEST = 'GET_UNITS_REQUEST';
export const GET_UNITS_SUCCESS = 'GET_UNITS_SUCCESS';
export const GET_UNITS_FAILURE = 'GET_UNITS_FAILURE';

// Add Units
export const ADD_UNITS_REQUEST = 'ADD_UNITS_REQUEST';
export const ADD_UNITS_SUCCESS = 'ADD_UNITS_SUCCESS';
export const ADD_UNITS_FAILURE = 'ADD_UNITS_FAILURE';
